# Generated by Django 5.0.8 on 2024-08-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeripheralRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware')], max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('reason', models.TextField(max_length=400)),
                ('employee_id', models.CharField(max_length=10)),
            ],
        ),
    ]
